#!/system/bin/sh

file_copy() {
	busybox cp -f $1 $2
	chown $3 $2/$1
	chmod $4 $2/$1 
}

loaded=`lsmod |grep vboxguest`
if [ "x$loaded" = x ]; then
	echo "Testing driver compatability with the kernel `uname -r`..."
	insmod vboxguest.ko || echo "Error: kernel version mismatch, rebuild guest drivers"
fi

modules_dir="/system/lib/modules/`uname -r`"
modules_extra_dir=$modules_dir/extra

if [ -d $mod_dir ]; then
	file_copy vboxguest.ko $modules_extra_dir root.root 0644
	file_copy vboxsf.ko $modules_extra_dir root.root 0644
	file_copy vboxvideo.ko $modules_extra_dir root.root 0644
	if [ -f $modules_dir/modules.dep ]; then
		modules_dep=$modules_dir/modules.dep
		vbox_dep=`grep vboxguest $modules_dep` 
		if [ "x$vbox_dep" = x ]; then
			echo "extra/vboxvideo.ko: extra/vboxguest.ko" >> $modules_dep
			echo "extra/vboxsf.ko: extra/vboxguest.ko" >> $modules_dep
			echo "extra/vboxvideo.ko: extra/vboxguest/vboxguest.ko kernel/drivers/gpu/drm/ttm/ttm.ko kernel/drivers/gpu/drm/drm_kms_helper.ko kernel/drivers/gpu/drm/drm.ko kernel/drivers/video/fbdev/core/fb_sys_fops.ko kernel/drivers/video/fbdev/core/sysfillrect.ko kernel/drivers/video/fbdev/core/syscopyarea.ko kernel/drivers/video/fbdev/core/sysimgblt.ko" >> $modules_dep
			echo "extra/vboxguest.ko:" >> $modules_dep
		fi
	fi
else
	echo "Error: no directory for guest drivers"
fi

cd src

if [ -d /system/etc/init ]; then
	file_copy init.vboxsf.rc /system/etc/init/ root.root 0644
else
	echo "Error: initrd must be rebuild"
fi
file_copy vboxsf.sh /system/bin/ root.root 0755

cd ..

if [ -f mount.vboxsf ]; then
	file_copy mount.vboxsf /system/bin/ root.root 0755
fi

if [ -f libinputflinger.so ]; then
	file_copy libinputflinger.so /system/lib/ root.root 0755
fi
